### ISSUE TITLE
Health check fails, dev-system

### ISSUE THREAD

**Issue by grcgit** [nasa/Common-Metadata-Repository#1413]
Been trying for few days to get the CMR running following the intructions in the top level README, seems to be an issue with the in-memory database.
Willing to try the oracle database if necessary, is there any additional information on how to setup the oracle database?

Running on Ubuntu 20.04

Can start the CMR through the REPL or JAR's

Test Results:
Ran 1886 tests containing 42050 assertions.
2 failures, 0 errors.

Health check below

curl -i -XGET localhost:3003/health?pretty=true
HTTP/1.1 503 Service Unavailable
Date: Wed, 05 Jan 2022 01:38:48 GMT
X-Frame-Options: SAMEORIGIN
Access-Control-Allow-Origin: *
X-XSS-Protection: 1; mode=block
CMR-Request-Id: 3db6030c-b99b-4c80-a277-4e6d2fa65181
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
Content-Type: application/json;charset=utf-8
X-Request-Id: 3db6030c-b99b-4c80-a277-4e6d2fa65181
Content-Length: 785
Server: Jetty(9.4.39.v20210325)

{
  "echo" : {
    "ok?" : true
  },
  "internal-metadata-db" : {
    "ok?" : false,
    "dependencies" : {
      "oracle" : {
        "ok?" : false,
        "problem" : "db-spec cmr.common.memory_db.connection.MemoryStore@7a96fb7 is missing a required parameter"
      }
    }
  },
  "indexer" : {
    "ok?" : false,
    "dependencies" : {
      "elastic_search" : {
        "ok?" : true
      },
      "echo" : {
        "ok?" : true
      },
      "metadata-db" : {
        "ok?" : false,
        "dependencies" : {
          "oracle" : {
            "ok?" : false,
            "problem" : "db-spec cmr.common.memory_db.connection.MemoryStore@52cab68c is missing a required parameter"
          }
        }
      },
      "message-queue" : {
        "ok?" : true
      }
    }
  }
}

**Comment by ygliuvt** [comment]
dev-system is the way for us to test CMR locally. By default, it uses the in-memory db (which is just a data structure in memory) rather than Oracle. This way, people don't have to have a local Oracle instance to develop with CMR. Because of this, the health check on Oracle fails (since there is no oracle). You can ignore the error message. Had you set up your dev-system to use a local Oracle instance (through the `(user/reset :db :external)` setting), you would see the health check report success on Oracle.
